language: ruby
rvm:
  - 2.5.1
addons:
  postgresql: '9.5'
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database crypto_test;' -U postgres
  - bundle exec sidekiq &
  - sleep 1
env:
  - RAILS_ENV=test
  - RAILS_VERSION=4.2.9
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test