language: ruby
before_script:
  - bundle exec sidekiq
  - sleep 1
rvm:
  - 2.5.1
addons:
  postgresql: '9.5'
services:
  - postgresql
  - redis-server
before_script:
  - gem install bundler
  - psql -c 'create database crypto_test;' -U postgres
env:
  - RAILS_ENV=test
  - RAILS_VERSION=4.2.9
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test